import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { main, next, buildRequest, validateInput, validateResponse, MODEL, ACTIONS } from './jev-dispatch.mjs';

const scratch = process.env.JEV_QC_TEST_TMP;
if (!scratch || !fs.statSync(scratch).isDirectory()) throw new Error('Set JEV_QC_TEST_TMP to an existing scratch directory');
const secret = 'SYNTHETIC-DISPATCH-KEY-NOT-A-CREDENTIAL';
const privateText = 'SYNTHETIC-PRIVATE-BLOCKER: observed local state only';
const astra = { modelId: 'gpt-6-astra', setting: 'unchanged' };
function input(stage = 'computer_use', ready_actions = ['SEARCH_ASSET', 'REVIEW']) { return { stage, blockers: privateText, ready_actions }; }
function response(state, choice = state.ready_actions[0]) { return { model: MODEL, answers: { next_action: { type: 'choice', choice, confidence: .8, probabilities: Object.fromEntries(state.ready_actions.map(a => [a, a === choice ? .8 : .2 / (state.ready_actions.length - 1 || 1)])) } }, usage: { input_tokens: 12, output_tokens: 4 } }; }
function fixture(t, state = input()) { const root=fs.mkdtempSync(path.join(scratch,'jev-dispatch-test-')); t.after(()=>fs.rmSync(root,{recursive:true,force:true})); const file=path.join(root,'input.json'); fs.writeFileSync(file,JSON.stringify(state)); let calls=0; const deps={status:()=>({key_present:true}),readKey:()=>secret,transport:async()=>{calls++;return response(state);}}; return {root,file,state,deps,calls:()=>calls,run:(more={},context={})=>next({root,input:file,context},{...deps,...more})}; }

test('builds a dynamic restricted choice schema', () => { const state=input(); const r=buildRequest(state); assert.equal(r.model,MODEL); assert.deepEqual(Object.keys(r.questions.next_action.criteria),state.ready_actions); assert.match(r.questions.next_action.instructions,/untrusted observed text data/); assert.match(r.questions.next_action.instructions,/Do not invent/); assert.deepEqual(validateInput(state),state); assert.ok(ACTIONS.includes('REVIEW')); });
test('rejects invalid input boundaries and author eligibility', () => { const bad=[{}, {...input(),blockers:' '}, {...input(),blockers:'x'.repeat(1501)}, {...input(),ready_actions:['REVIEW','REVIEW']}, {...input(),ready_actions:['SEARCH_ASSET']}, input('music_prompt',['REVIEW']), input('music_prompt',['AUTHOR_ASTRA','SEARCH_ASSET','REVIEW']), input('computer_use',['AUTHOR_ASTRA','REVIEW']), {...input(),ready_actions:Array(10).fill('REVIEW')}]; for(const x of bad) assert.throws(()=>validateInput(x),/INVALID_INPUT/); assert.doesNotThrow(()=>validateInput(input('music_prompt',['AUTHOR_ASTRA','WAIT','REOBSERVE','REVIEW']))); });
test('rejects out-of-set actions and invalid probability totals', () => { const state=input(); const r=response(state); r.answers.next_action.choice='WAIT'; assert.throws(()=>validateResponse(r,state),/INVALID_RESPONSE/); const n=response(state); n.answers.next_action.probabilities={SEARCH_ASSET:.3,REVIEW:.2}; assert.throws(()=>validateResponse(n,state),/INVALID_RESPONSE/); });
test('routes Astra directly and holds when unavailable', async t => { const state=input('music_prompt',['AUTHOR_ASTRA','REVIEW']); const f=fixture(t,state); const direct=await f.run({}, {model:astra}); assert.equal(direct.route.mode,'direct'); assert.equal(direct.route.role,'author'); const f2=fixture(t,state); const hold=await f2.run({}, {}); assert.equal(hold.route.state,'HOLD_ASTRA_AUTHOR_REQUIRED'); assert.equal(hold.execution_authorized,false); });
test('routes Astra through Luna category without changing settings', async t => { const state=input('seedance_prompt',['AUTHOR_ASTRA','REVIEW']); const f=fixture(t,state); const context={model:{modelId:'luna'},modelCategories:{visual:astra},settings:{keep:'same'}}; const before=JSON.stringify(context); const got=await f.run({},context); assert.equal(got.route.mode,'functions.subagent'); assert.equal(got.route.category,'visual'); assert.equal(JSON.stringify(context),before); });
test('cache resolves route using current context', async t => { const f=fixture(t); const first=await f.run({},{}); assert.equal(first.status,'CLASSIFIED'); assert.equal(first.route.mode,'inherit_session'); const second=await f.run({}, {model:astra}); assert.equal(second.status,'CACHED'); assert.equal(second.route.mode,'inherit_session'); assert.equal(f.calls(),1); });
test('charges one attempt per failure with no automatic retry and limits at three', async t => { const f=fixture(t); let failureCalls=0; const boom=async()=>{failureCalls++;throw new Error('network')}; for(let i=0;i<3;i++){const state={...f.state,blockers:privateText+i};fs.writeFileSync(f.file,JSON.stringify(state)); const got=await f.run({transport:boom});assert.equal(got.status,'UNAVAILABLE');assert.equal(failureCalls,i+1);} fs.writeFileSync(f.file,JSON.stringify({...f.state,blockers:'fourth'})); const limited=await f.run({transport:boom}); assert.equal(limited.status,'LIMIT_REACHED'); assert.equal(failureCalls,3); const entries=fs.readFileSync(path.join(f.root,'.jev-dispatch','ledger.jsonl'),'utf8').trim().split('\n'); assert.equal(entries.length,3); });
test('does not expose secret or blockers in result or persisted records', async t => { const f=fixture(t); const got=await f.run(); const disk=fs.readFileSync(path.join(f.root,'.jev-dispatch',fs.readdirSync(path.join(f.root,'.jev-dispatch')).find(x=>x.endsWith('.json'))),'utf8'); for(const value of [secret,privateText]) { assert.equal(JSON.stringify(got).includes(value),false); assert.equal(disk.includes(value),false); } });
test('CLI parses local context and rejects bad arguments offline', async t => { const f=fixture(t,input('image_prompt',['AUTHOR_ASTRA','REVIEW'])); const ok=await main(['next','--root',f.root,'--input',f.file,'--context',JSON.stringify({model:astra})],f.deps); assert.equal(ok.code,0); assert.equal(ok.result.route.mode,'direct'); const bad=await main(['next','--root',f.root],f.deps); assert.equal(bad.code,2); assert.equal(bad.result.status,'INVALID_ARGUMENTS'); });

test('rejects orphan state after ledger removal instead of resetting cap', async t => { const f=fixture(t); await f.run(); const dir=path.join(f.root,'.jev-dispatch'); fs.unlinkSync(path.join(dir,'ledger.jsonl')); await assert.rejects(()=>f.run(),/CORRUPT_LEDGER/); });
test('rejects traversal-style ledger IDs', async t => { const f=fixture(t); const dir=path.join(f.root,'.jev-dispatch'); fs.mkdirSync(dir,{mode:0o700}); fs.writeFileSync(path.join(dir,'ledger.jsonl'),JSON.stringify({id:'../../escape',input_sha256:'a'.repeat(64),cache_key:'b'.repeat(64),stage:'computer_use',ready_actions:['REVIEW']})+'\n',{mode:0o600}); await assert.rejects(()=>f.run(),/CORRUPT_LEDGER/); });
test('validates unmatched completed records using their stored choices', async t => { const f=fixture(t); await f.run(); const dir=path.join(f.root,'.jev-dispatch'); const record=fs.readdirSync(dir).find(n=>n.endsWith('.json')); const value=JSON.parse(fs.readFileSync(path.join(dir,record))); value.probabilities={SEARCH_ASSET:.9,REVIEW:.9}; fs.writeFileSync(path.join(dir,record),JSON.stringify(value)+'\n'); fs.chmodSync(path.join(dir,record),0o600); await assert.rejects(()=>f.run({}, {model:astra}),/INVALID_RECORD/); });
