import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const fast = new Function('return (' + await fs.readFile(new URL('./runway-fastlane.js',import.meta.url),'utf8') + ')')();
const url='https://app.runwayml.com/observed-test-only';
const mode='- radio "Video" [ref=e1] [checked]\n- radio "Reference" [ref=e2] [checked]\n- radio "Keyframe" [ref=e3]\n';
const prompt='- textbox "Prompt" [ref=e4]\n';
const slot='- button "View Image 1 larger" [ref=e9]\n';
const picker='- dialog "Asset selector":\n  - textbox "Search" [ref=e6]\n  - button "bound.png Image • Upload" [ref=e7]\n';
const gate=()=>({passed:true,observed_at:new Date().toISOString()});
function setup(trees, text='') {
  const calls=[], logs=[]; let i=0,value=text;
  const env={page:{url:()=>url, locator:r=>({click:async()=>calls.push(['click',r]),dblclick:async()=>calls.push(['dblclick',r]),fill:async v=>{calls.push(['fill',r,v]);value=v;},evaluate:async f=>f({value}),count:async()=>1,getAttribute:async()=> 'file',setInputFiles:async files=>calls.push(['upload',files])})}, snapshot:async()=>{const body=trees[Math.min(i++,trees.length-1)];const tree=body.includes('[url=')?body:'- title: "Runway" [url='+url+']\n'+body;return{tree,diff:tree};},log:s=>logs.push(s)};
  return {env,calls,logs};
}
const job=(action,extra={})=>({action,expected_url:url,mode_gate:gate(),...extra});
const payload=()=>({language_status:'CURRENT_POLICY_VALIDATED',state:'READY_FOR_PROVIDER_INPUT',stage:'seedance_prompt',provider:'runway_web',payload_sha256:'a'.repeat(64),payload:{required_author:'gpt-6-astra',stage:'seedance_prompt',provider:'runway_web',prompt:'테스트 원문',references:[]}});
test('no Generate, approve or invented action is executable',async()=>{for(const action of ['GENERATE','APPROVE','RETRY','AUTHOR_ASTRA']){const x=setup([mode]);assert.equal((await fast(x.env,job(action))).status,'UNSUPPORTED_ACTION');assert.equal(x.calls.length,0);}});
test('wrong session blocks before action',async()=>{const x=setup([mode]);assert.equal((await fast(x.env,job('SEARCH_ASSET',{expected_url:url+'wrong'}))).status,'SESSION_MISMATCH');assert.equal(x.logs.length,1);assert.equal(x.calls.length,0);});
test('Keyframe mode blocks input',async()=>{const x=setup([mode.replace('"Reference" [ref=e2] [checked]','"Reference" [ref=e2]')]);assert.equal((await fast(x.env,job('FILL_PROMPT'))).status,'BLOCKED_REFERENCE_MODE_NOT_CONFIRMED');assert.equal(x.calls.length,0);});
test('search opens and fills in a single bounded call with every snapshot logged',async()=>{const x=setup([mode+'- button "Reference" [ref=e5]',mode+picker,mode+picker]);const r=await fast(x.env,job('SEARCH_ASSET',{asset_name:'bound.png'}));assert.equal(r.status,'SEARCH_OBSERVED');assert.deepEqual(x.calls,[['click','e5'],['fill','e6','bound.png']]);assert.equal(x.logs.length,3);assert.equal(r.empty_result_is_not_upload_permission,true);});
test('search cannot use guessed or duplicate controls',async()=>{const x=setup([mode+'- button "Reference" [ref=e5]\n- button "Reference" [ref=e8]']);assert.equal((await fast(x.env,job('SEARCH_ASSET',{asset_name:'bound.png'}))).status,'SEARCH_ENTRY_NOT_OBSERVED');assert.equal(x.calls.length,0);});
test('selection confirms one added ordered slot',async()=>{const x=setup([mode+picker,mode+slot]);assert.equal((await fast(x.env,job('SELECT_EXISTING',{binding_confirmed:true,candidate:{role:'button',name:'bound.png Image • Upload'},expected_count:1}))).status,'REFERENCE_SLOT_ACCEPTED');assert.deepEqual(x.calls,[['dblclick','e7']]);});
test('existing reference is not toggled again',async()=>{const x=setup([mode+slot+picker]);assert.equal((await fast(x.env,job('SELECT_EXISTING',{binding_confirmed:true,candidate:{role:'button',name:'bound.png Image • Upload'},expected_count:1}))).status,'REFERENCES_ALREADY_PRESENT_VERIFY');assert.equal(x.calls.length,0);});
test('unknown identity cannot select',async()=>{const x=setup([mode+picker]);assert.equal((await fast(x.env,job('SELECT_EXISTING',{candidate:{role:'button',name:'bound.png Image • Upload'},expected_count:1}))).status,'ASSET_BINDING_REQUIRED');});
test('only verified payload is copied and exact accepted text checked',async()=>{const x=setup([mode+prompt,mode+prompt]);const r=await fast(x.env,job('FILL_PROMPT',{verified_submission:payload(),expected_previous_prompt:''}));assert.equal(r.status,'PROMPT_ACCEPTED');assert.equal(x.calls.length,1);assert.equal(x.calls[0][2],'테스트 원문');assert.equal(x.logs.length,2);});
test('unverified or mismatched references block prompt fill',async()=>{for(const tree of [mode+prompt,mode+prompt+slot]){const x=setup([tree]);const p=payload();if(!tree.includes('Image 1'))p.payload.required_author='other';assert.notEqual((await fast(x.env,job('FILL_PROMPT',{verified_submission:p,expected_previous_prompt:''}))).status,'PROMPT_ACCEPTED');assert.equal(x.calls.length,0);}});
test('preserve unexpected existing text and skip identical desired text',async()=>{for(const [text,status] of [['other work','PRESERVE_EXISTING_PROMPT'],['테스트 원문','PROMPT_ALREADY_ACCEPTED']]){const x=setup([mode+prompt],text);assert.equal((await fast(x.env,job('FILL_PROMPT',{verified_submission:payload(),expected_previous_prompt:''}))).status,status);assert.equal(x.calls.length,0);}});
test('stale mode gate prevents attachment/input',async()=>{const x=setup([mode+prompt]);assert.equal((await fast(x.env,job('FILL_PROMPT',{mode_gate:{passed:true,observed_at:new Date(Date.now()-31000).toISOString()},verified_submission:payload(),expected_previous_prompt:''}))).status,'MODE_GATE_REQUIRED');assert.equal(x.calls.length,0);});
test('upload requires durable claim and never implies accepted attachment',async()=>{const x=setup([mode,mode]);let claimed=false;x.env.claimUpload=async()=>{if(claimed)return false;claimed=true;return true;};const j=job('UPLOAD_FIRST',{search_absence_verified:true,files_verified:true,expected_existing_count:0,observed_file_input_selector:'input.observed',files:['/verified.png']});assert.equal((await fast(x.env,j)).status,'UPLOAD_DISPATCHED_UNCONFIRMED');assert.equal((await fast(x.env,j)).status,'UPLOAD_ALREADY_ATTEMPTED_REOBSERVE');assert.equal(x.calls.length,1);});
test('an action error observes once and never retries',async()=>{const x=setup([mode+picker,mode+picker]);x.env.page.locator=()=>({fill:async()=>{x.calls.push('fill');throw Error('timeout');}});assert.equal((await fast(x.env,job('SEARCH_ASSET',{asset_name:'bound.png'}))).status,'ACTION_UNCONFIRMED_REOBSERVE');assert.deepEqual(x.calls,['fill']);assert.equal(x.logs.length,2);});

test('observed empty Runway editor LF is not mistaken for another prompt',async()=>{const x=setup([mode+prompt,mode+prompt],'\n');const r=await fast(x.env,job('FILL_PROMPT',{verified_submission:payload(),expected_previous_prompt:''}));assert.equal(r.status,'PROMPT_ACCEPTED');assert.deepEqual(x.calls,[['fill','e4','테스트 원문']]);});

test('open Asset selector blocks prompt input despite underlying Prompt ref',async()=>{const x=setup([mode+prompt+picker]);const r=await fast(x.env,job('FILL_PROMPT',{verified_submission:payload(),expected_previous_prompt:''}));assert.equal(r.status,'BLOCKING_DIALOG_CLOSE_AND_REOBSERVE');assert.equal(x.calls.length,0);});
test('fresh snapshot identity supersedes stale page.url cache',async()=>{const x=setup([mode+prompt]);x.env.page.url=()=>url+'?old=newSession';const r=await fast(x.env,job('FILL_PROMPT',{verified_submission:payload(),expected_previous_prompt:''}));assert.equal(r.status,'PROMPT_ACCEPTED');});
test('matching stale page.url cannot hide different live session',async()=>{const x=setup(['- title: "Runway" [url='+url+'?other=session]\n'+mode+prompt]);const r=await fast(x.env,job('FILL_PROMPT',{verified_submission:payload(),expected_previous_prompt:''}));assert.equal(r.status,'SESSION_MISMATCH');assert.equal(x.calls.length,0);});

test('legacy language evidence cannot authorize fresh prompt fill',async()=>{const x=setup([mode+prompt]);const v=payload();v.language_status='LEGACY_UNSPECIFIED_READ_ONLY';assert.equal((await fast(x.env,job('FILL_PROMPT',{verified_submission:v,expected_previous_prompt:''}))).status,'CURRENT_LANGUAGE_CONTRACT_REQUIRED');assert.equal(x.calls.length,0);});
