#!/usr/bin/env node
import { createHash, randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import * as fs from 'node:fs/promises';

const MARKER_START = '<!-- aside-video-workflow:start -->';
const MARKER_END = '<!-- aside-video-workflow:end -->';
const SOURCE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'aside-skills');
const HASH = /^[a-f0-9]{64}$/;
const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');
const fail = message => { throw new Error(message); };

function relOk(rel) { return typeof rel === 'string' && rel.length > 0 && !path.isAbsolute(rel) && !rel.split(/[\\/]/).some(part => !part || part === '.' || part === '..'); }
async function lstatRegular(file, label = file) { const st = await fs.lstat(file).catch(err => fail(`${label}: ${err.code}`)); if (st.isSymbolicLink()) fail(`${label}: symlinks are not allowed`); if (!st.isFile()) fail(`${label}: expected a regular file`); }
async function lstatDir(dir, label = dir) { const st = await fs.lstat(dir).catch(err => fail(`${label}: ${err.code}`)); if (st.isSymbolicLink()) fail(`${label}: symlinks are not allowed`); if (!st.isDirectory()) fail(`${label}: expected a directory`); }
async function assertRealDirectory(dir, label) { if (!path.isAbsolute(dir)) fail(`${label} must be an absolute path`); await lstatDir(dir, label); if (await fs.realpath(dir) !== path.resolve(dir)) fail(`${label} must not be a symlinked path`); }
async function listFiles(root, relative = '') { await lstatDir(path.join(root, relative), relative || root); const out = []; for (const entry of await fs.readdir(path.join(root, relative), { withFileTypes: true })) { const rel = relative ? path.posix.join(relative, entry.name) : entry.name; const st = await fs.lstat(path.join(root, rel)); if (st.isSymbolicLink()) fail(`${rel}: symlinks are not allowed`); if (st.isDirectory()) out.push(...await listFiles(root, rel)); else if (st.isFile()) out.push(rel); else fail(`${rel}: unsupported filesystem entry`); } return out; }
function allowedSource(rel) { return rel === 'AGENTS.fragment.md' || rel === 'manifest.json' || rel === 'aside-video/SKILL.md' || /^aside-video\/scripts\/.+\.(?:mjs|js)$/.test(rel) || /^aside-video\/references\/.+\.(?:md|json)$/.test(rel); }
const expectedSkillPath = rel => rel.startsWith('aside-video/') ? rel.slice('aside-video/'.length) : null;
async function assertSourceDirectories(root, relative = '') { for (const entry of await fs.readdir(path.join(root, relative), { withFileTypes: true })) { if (!entry.isDirectory()) continue; const rel = relative ? path.posix.join(relative, entry.name) : entry.name; const st = await fs.lstat(path.join(root, rel)); if (st.isSymbolicLink()) fail(`${rel}: symlinks are not allowed`); if (rel !== 'aside-video' && rel !== 'aside-video/scripts' && rel !== 'aside-video/references' && !rel.startsWith('aside-video/scripts/') && !rel.startsWith('aside-video/references/')) fail(`unexpected source directory: ${rel}`); await assertSourceDirectories(root, rel); } }
async function sourceFiles(sourceRoot) { await assertRealDirectory(sourceRoot, 'source root'); await assertSourceDirectories(sourceRoot); const all = await listFiles(sourceRoot); for (const rel of all) if (!allowedSource(rel)) fail(`unexpected source file: ${rel}`); for (const rel of ['AGENTS.fragment.md', 'aside-video/SKILL.md']) if (!all.includes(rel)) fail(`missing required source file: ${rel}`); return all.filter(rel => rel !== 'manifest.json').sort(); }
async function sourceEntries(sourceRoot) { return Promise.all((await sourceFiles(sourceRoot)).map(async rel => ({ path: rel, sha256: sha256(await fs.readFile(path.join(sourceRoot, rel))) }))); }
function validateManifestShape(manifest, expectedPaths) { if (!manifest || manifest.version !== 1 || !Array.isArray(manifest.files)) fail('invalid manifest format'); const seen = new Set(); if (manifest.files.length !== expectedPaths.length) fail('manifest file set does not match source'); for (const item of manifest.files) { if (!item || !relOk(item.path) || !HASH.test(item.sha256) || seen.has(item.path)) fail('invalid manifest entry'); seen.add(item.path); } for (const p of expectedPaths) if (!seen.has(p)) fail(`manifest missing source path: ${p}`); }
export async function validateFrozenSource({ sourceRoot = SOURCE_ROOT } = {}) { const entries = await sourceEntries(sourceRoot); const manifestPath = path.join(sourceRoot, 'manifest.json'); await lstatRegular(manifestPath, 'manifest.json'); let manifest; try { manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8')); } catch { fail('invalid manifest JSON'); } validateManifestShape(manifest, entries.map(x => x.path)); const hashes = new Map(manifest.files.map(x => [x.path, x.sha256])); return { entries, mismatches: entries.filter(x => hashes.get(x.path) !== x.sha256).map(x => x.path) }; }
export async function freezeSource({ sourceRoot = SOURCE_ROOT } = {}) { const manifest = { version: 1, files: await sourceEntries(sourceRoot) }; await fs.writeFile(path.join(sourceRoot, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n', { mode: 0o600 }); return manifest; }
async function ensureDirBelow(root, rel) { if (!relOk(rel)) fail('unsafe relative directory'); let cur = root; for (const part of rel.split('/')) { cur = path.join(cur, part); const st = await fs.lstat(cur).catch(err => err.code === 'ENOENT' ? null : fail(`${cur}: ${err.code}`)); if (!st) { await fs.mkdir(cur); continue; } if (st.isSymbolicLink() || !st.isDirectory()) fail(`unsafe destination directory: ${path.relative(root, cur)}`); } return cur; }
async function assertSafeParents(root, rel) { if (!relOk(rel)) fail('unsafe relative path'); let cur = root; for (const part of rel.split('/')) { cur = path.join(cur, part); const st = await fs.lstat(cur).catch(err => err.code === 'ENOENT' ? null : fail(`${cur}: ${err.code}`)); if (!st) return; if (st.isSymbolicLink()) fail(`unsafe destination directory: ${path.relative(root, cur)}`); if (!st.isDirectory() && part !== rel.split('/').at(-1)) fail(`unsafe destination directory: ${path.relative(root, cur)}`); } }
function markerBlock(fragment) { const starts = fragment.split(MARKER_START).length - 1, ends = fragment.split(MARKER_END).length - 1; const a = fragment.indexOf(MARKER_START), b = fragment.indexOf(MARKER_END); if (starts !== 1 || ends !== 1 || a > b) fail('fragment must contain one valid managed marker block'); return fragment.slice(a, b + MARKER_END.length); }
function spliceManaged(current, block) { const starts = current.split(MARKER_START).length - 1, ends = current.split(MARKER_END).length - 1; const a = current.indexOf(MARKER_START), b = current.indexOf(MARKER_END); if (starts === 0 && ends === 0) return current + (current && !current.endsWith('\n') ? '\n' : '') + (current ? '\n' : '') + block; if (starts !== 1 || ends !== 1 || a > b) fail('account AGENTS.md has malformed managed markers'); return current.slice(0, a) + block + current.slice(b + MARKER_END.length); }
async function readOptionalRegular(file, label) { const st = await fs.lstat(file).catch(err => err.code === 'ENOENT' ? null : fail(`${label}: ${err.code}`)); if (!st) return null; if (st.isSymbolicLink() || !st.isFile()) fail(`${label}: expected a regular non-symlink file`); return fs.readFile(file); }
async function installedUnexpected(skillRoot, expected) { const st = await fs.lstat(skillRoot).catch(err => err.code === 'ENOENT' ? null : fail(`installed skill: ${err.code}`)); if (!st) return []; if (st.isSymbolicLink() || !st.isDirectory()) fail('installed skill path is unsafe'); return (await listFiles(skillRoot)).filter(x => !expected.has(x)); }
async function desired({ sourceRoot, accountRoot }) { const frozen = await validateFrozenSource({ sourceRoot }); const text = (await fs.readFile(path.join(sourceRoot, 'AGENTS.fragment.md'), 'utf8')).replaceAll('<accountRoot>', accountRoot); return { frozen, fragment: markerBlock(text) }; }
export async function checkDeployment({ sourceRoot = SOURCE_ROOT, accountRoot } = {}) { await assertRealDirectory(accountRoot, 'account root'); const problems = []; let plan; try { plan = await desired({ sourceRoot, accountRoot }); } catch (err) { return { ok: false, problems: [`source: ${err.message}`] }; } for (const p of plan.frozen.mismatches) problems.push(`source manifest mismatch: ${p}`); const expected = new Set(plan.frozen.entries.map(x => expectedSkillPath(x.path)).filter(Boolean)); const skillRoot = path.join(accountRoot, 'skills', 'user', 'aside-video'); try { await assertSafeParents(accountRoot, 'skills/user/aside-video'); for (const p of await installedUnexpected(skillRoot, expected)) problems.push(`unexpected installed file: skills/user/aside-video/${p}`); for (const entry of plan.frozen.entries.filter(x => expectedSkillPath(x.path))) { const rel = expectedSkillPath(entry.path), bytes = await readOptionalRegular(path.join(skillRoot, rel), 'installed file'); if (!bytes) problems.push(`missing installed file: skills/user/aside-video/${rel}`); else if (sha256(bytes) !== entry.sha256) problems.push(`changed installed file: skills/user/aside-video/${rel}`); } const agents = await readOptionalRegular(path.join(accountRoot, 'AGENTS.md'), 'account AGENTS.md'); if (!agents) problems.push('missing managed fragment: AGENTS.md'); else if (agents.toString() !== spliceManaged(agents.toString(), plan.fragment)) problems.push('changed managed fragment: AGENTS.md'); } catch (err) { problems.push(`account: ${err.message}`); } return { ok: problems.length === 0, problems }; }
async function backupFile(root, unique, rel, bytes) { await ensureDirBelow(root, path.posix.dirname(`.workflow-backups/${unique}/${rel}`)); await fs.writeFile(path.join(root, '.workflow-backups', unique, rel), bytes, { mode: 0o600 }); }
export async function applyDeployment({ sourceRoot = SOURCE_ROOT, accountRoot } = {}) { await assertRealDirectory(accountRoot, 'account root'); const plan = await desired({ sourceRoot, accountRoot }); if (plan.frozen.mismatches.length) fail(`source manifest mismatch: ${plan.frozen.mismatches.join(', ')}`); const expected = new Set(plan.frozen.entries.map(x => expectedSkillPath(x.path)).filter(Boolean)); const skillRoot = path.join(accountRoot, 'skills', 'user', 'aside-video'); await assertSafeParents(accountRoot, 'skills/user/aside-video'); const unexpected = await installedUnexpected(skillRoot, expected); if (unexpected.length) fail(`unexpected installed file: skills/user/aside-video/${unexpected[0]}`); const agentsPath = path.join(accountRoot, 'AGENTS.md'), oldAgents = await readOptionalRegular(agentsPath, 'account AGENTS.md'); const nextAgents = spliceManaged(oldAgents ? oldAgents.toString() : '', plan.fragment); await ensureDirBelow(accountRoot, 'skills/user/aside-video'); const unique = new Date().toISOString().replace(/[:.]/g, '-') + '-' + randomUUID(); let backedUp = false; for (const entry of plan.frozen.entries.filter(x => expectedSkillPath(x.path))) { const rel = expectedSkillPath(entry.path), dest = path.join(skillRoot, rel), old = await readOptionalRegular(dest, 'installed file'); const bytes = await fs.readFile(path.join(sourceRoot, entry.path)); if (sha256(bytes) !== entry.sha256) fail('source changed during apply: ' + entry.path); if (old && !old.equals(bytes)) { await backupFile(accountRoot, unique, `skills/user/aside-video/${rel}`, old); backedUp = true; } await ensureDirBelow(accountRoot, path.posix.dirname(`skills/user/aside-video/${rel}`)); if (!old || !old.equals(bytes)) await fs.writeFile(dest, bytes, { mode: 0o600 }); } if (oldAgents && oldAgents.toString() !== nextAgents) { await backupFile(accountRoot, unique, 'AGENTS.md', oldAgents); backedUp = true; } if (!oldAgents || oldAgents.toString() !== nextAgents) await fs.writeFile(agentsPath, nextAgents, { mode: 0o600 }); const after = await checkDeployment({ sourceRoot, accountRoot }); if (!after.ok) fail('post-apply parity failed: ' + after.problems.join(', ')); return { ok: true, backup: backedUp ? path.join('.workflow-backups', unique) : null }; }
function usage() { return 'usage: deploy_aside_workflow.mjs --freeze | (--check|--apply) --account-root ABS'; }
export async function main(argv = process.argv.slice(2)) { let mode = null, accountRoot; for (let i = 0; i < argv.length; i++) { const x = argv[i]; if (['--freeze', '--check', '--apply'].includes(x)) { if (mode) fail(usage()); mode = x; } else if (x === '--account-root') { if (accountRoot !== undefined) fail(usage()); accountRoot = argv[++i]; if (!accountRoot) fail(usage()); } else fail(usage()); } if (!mode || (mode === '--freeze' ? accountRoot : !accountRoot)) fail(usage()); if (mode === '--freeze') { const m = await freezeSource(); console.log(`FROZEN ${m.files.length} source files`); return 0; } if (mode === '--check') { const r = await checkDeployment({ accountRoot }); console.log(r.ok ? 'PARITY OK' : `PARITY MISMATCH\n${r.problems.map(p => `- ${p}`).join('\n')}`); return r.ok ? 0 : 1; } const r = await applyDeployment({ accountRoot }); console.log(`APPLIED${r.backup ? ` backup=${r.backup}` : ''}`); return 0; }
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main().then(code => { process.exitCode = code; }).catch(err => { console.error(`ERROR ${err.message}`); process.exitCode = 2; });
